### ISSUE TITLE
Build script improvement - find Phoenix Edition

### ISSUE THREAD

**Issue by vivid-pixel** [boxgaming/gx#5]
Here's my modification to also search for QB64PE

**gx\mapmaker\build.bat**:
```
@echo off
if exist "%QB64_HOME%\qb64.exe"  (
	echo Using %QB64_HOME%...
	copy %CD%\inform\gx_falcon.h %QB64_HOME%
	"%QB64_HOME%\qb64.exe" -x %CD%\MapMaker.bas -o %CD%\MapMaker.exe
) else (
	if exist "%QB64_HOME%\qb64pe.exe" (
	echo Using %QB64_HOME%...
	copy %CD%\inform\gx_falcon.h %QB64_HOME%
	"%QB64_HOME%\qb64pe.exe" -x %CD%\MapMaker.bas -o %CD%\MapMaker.exe
  ) else (
	echo QB64 not found at [%QB64_HOME%].
	echo Please ensure the QB64_HOME variable is set to the correct path.
  )
)
```

There we go, easy compatibility! 

Another snag I had during the install was setting the QB64_HOME variable.
Under Windows PowerShell on Windows 11, I had to set the variable inside the main build script, rather than in the terminal prior to running. Otherwise the variable was always blank when the script accessed it. Maybe just something I'm doing wrong.
**gx\build.bat**:
```
set QB64_HOME="C:\Users\admin\OneDrive\Documents\qb64pe\"
cd mapmaker
call build
cd ..
cd tools
call build
cd ..
```

**Comment by boxgaming** [comment]
Thanks for the suggestion.  I'll incorporate more flexibility in the build script to account for multiple QB64 versions in the next release.

Regarding the QB64_HOME variable.  I would recommend setting this as an environment variable so you do not have to set it each time you want to run the build:

https://thegeekpage.com/environment-variables-in-windows-11

**Comment by boxgaming** [comment]
I forgot to update this issue when I put out the 0.5.0 release.  You can now use the build scripts with QB64 or QB64PE.
